#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v4
# autospec commit: 3d985eb
#
Name     : grantlee
Version  : 5.3.1
Release  : 13
URL      : https://github.com/steveire/grantlee/archive/v5.3.1/grantlee-5.3.1.tar.gz
Source0  : https://github.com/steveire/grantlee/archive/v5.3.1/grantlee-5.3.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: grantlee-lib = %{version}-%{release}
Requires: grantlee-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : qt6base-dev
BuildRequires : qtbase-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtdeclarative-dev
BuildRequires : qtscript-dev
BuildRequires : qttools-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
The Grantlee Libraries
======================
[![OSX/Linux Build Status](https://travis-ci.org/steveire/grantlee.svg?branch=master)](https://travis-ci.org/steveire/grantlee)
[![Windows Build status](https://ci.appveyor.com/api/projects/status/github/steveire/grantlee?branch=master&svg=true)](https://ci.appveyor.com/project/steveire/grantlee/branch/master)

%package dev
Summary: dev components for the grantlee package.
Group: Development
Requires: grantlee-lib = %{version}-%{release}
Provides: grantlee-devel = %{version}-%{release}
Requires: grantlee = %{version}-%{release}

%description dev
dev components for the grantlee package.


%package lib
Summary: lib components for the grantlee package.
Group: Libraries
Requires: grantlee-license = %{version}-%{release}

%description lib
lib components for the grantlee package.


%package license
Summary: license components for the grantlee package.
Group: Default

%description license
license components for the grantlee package.


%prep
%setup -q -n grantlee-5.3.1
cd %{_builddir}/grantlee-5.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1710453995
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DGRANTLEE_BUILD_WITH_QT6=ON
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DGRANTLEE_BUILD_WITH_QT6=ON
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test || :
cd ../clr-build-avx2;
make test || : || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1710453995
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/grantlee
cp %{_builddir}/grantlee-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/grantlee/ce930e36882c6e85c21362d4b51f564863802a75 || :
export GOAMD64=v2
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/grantlee/abstractlocalizer.h
/usr/include/grantlee/abstractmarkupbuilder.h
/usr/include/grantlee/bbcodebuilder.h
/usr/include/grantlee/cachingloaderdecorator.h
/usr/include/grantlee/context.h
/usr/include/grantlee/engine.h
/usr/include/grantlee/exception.h
/usr/include/grantlee/filter.h
/usr/include/grantlee/filterexpression.h
/usr/include/grantlee/grantlee_templates_export.h
/usr/include/grantlee/grantlee_textdocument_export.h
/usr/include/grantlee/grantlee_version.h
/usr/include/grantlee/markupdirector.h
/usr/include/grantlee/mediawikimarkupbuilder.h
/usr/include/grantlee/metatype.h
/usr/include/grantlee/node.h
/usr/include/grantlee/outputstream.h
/usr/include/grantlee/parser.h
/usr/include/grantlee/plaintextmarkupbuilder.h
/usr/include/grantlee/qtlocalizer.h
/usr/include/grantlee/rendercontext.h
/usr/include/grantlee/safestring.h
/usr/include/grantlee/taglibraryinterface.h
/usr/include/grantlee/template.h
/usr/include/grantlee/templateloader.h
/usr/include/grantlee/texthtmlbuilder.h
/usr/include/grantlee/token.h
/usr/include/grantlee/typeaccessor.h
/usr/include/grantlee/util.h
/usr/include/grantlee/variable.h
/usr/include/grantlee_templates.h
/usr/include/grantlee_textdocument.h
/usr/lib64/cmake/Grantlee5/Grantlee5Config.cmake
/usr/lib64/cmake/Grantlee5/Grantlee5ConfigVersion.cmake
/usr/lib64/cmake/Grantlee5/GrantleeMacros.cmake
/usr/lib64/cmake/Grantlee5/GrantleeTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Grantlee5/GrantleeTargets.cmake
/usr/lib64/libGrantlee_Templates.so
/usr/lib64/libGrantlee_TextDocument.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/grantlee/5.3/grantlee_defaultfilters.so
/V3/usr/lib64/grantlee/5.3/grantlee_defaulttags.so
/V3/usr/lib64/grantlee/5.3/grantlee_i18ntags.so
/V3/usr/lib64/grantlee/5.3/grantlee_loadertags.so
/V3/usr/lib64/libGrantlee_Templates.so.5.3.0
/V3/usr/lib64/libGrantlee_TextDocument.so.5.3.0
/usr/lib64/grantlee/5.3/grantlee_defaultfilters.so
/usr/lib64/grantlee/5.3/grantlee_defaulttags.so
/usr/lib64/grantlee/5.3/grantlee_i18ntags.so
/usr/lib64/grantlee/5.3/grantlee_loadertags.so
/usr/lib64/libGrantlee_Templates.so.5
/usr/lib64/libGrantlee_Templates.so.5.3.0
/usr/lib64/libGrantlee_TextDocument.so.5
/usr/lib64/libGrantlee_TextDocument.so.5.3.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/grantlee/ce930e36882c6e85c21362d4b51f564863802a75
